**张量（tensor）：**
一般来说，当前所有机器学习的系统都适用张量作为基本的数据结构。将数据存储在多维Numpy数组中（即：张量）TensorFlow是以张量tensor命名的。
张量tensor是一个数据容器，这里说的数据几乎总是数值数据。
矩阵是二维张量。张量可以看作矩阵向任意维度的推广。

**0D张量：**
仅包含一个数字的张量叫标量（scalar）也叫标量张量/零维张量/0D张量
在Numpy中，一个float32或float64的数字就是一个标量张量。

可以用ndim来查看一个Numpy张量的轴个数。

标量张量有0个轴（ndim==0）


张量轴的个数也叫阶（rank）


In [1]:
import numpy as np
x=np.array(12)
x.ndim

0

**1D张量（向量vector）：**
数字组成的数组叫1维张量，或者向量。1维张量/向量只有一个轴

In [22]:
a=np.array([1,2,3,4,5])
a.ndim
#ndim显示张量有几个轴，向量vector是一维张量，一维就是一个轴

1

In [23]:
#矩阵是2D张量，有两个轴,rows&columns,matrix是vector组成的，即2D张量是1D张量组成的
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x.ndim

2

In [24]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
#同理，3D张量是2D张量组成的，将多个矩阵组合成一个数组，得到一个3D tensor
import numpy as np
y=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
y.ndim
e=y.ndim
print(e)

3


In [17]:
#以此类推，4D张量是3D张量组成的
z=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]],
           [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]],
           [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]])
z.ndim

4

tensor是由3个关键属性来定义的

属性1:ndim 即轴的个数，0轴tensor是标量（一个数），1轴tensor是vector可以写成list的形式，2轴tensor是矩阵matrix，3Dtensor是由2Dtensor组成的，以此类推

属性2:形状，是一个整数元祖，表示tensor在每个轴上有几个元素（每个轴上的数据量）

属性3:数据类型dtype，tensor中包含的数据的类型，float32，float64，uint8

In [21]:
print(x.shape)#x是一个2D的tensor，因此shape有两位（1位，2位），x是3行4列的矩阵，因此第一个轴‘row’中的数据量为3，第二个轴‘column’的数据量为4
print(y.shape)#y是一个3个x组成的3D的tensor，因此它的shape有三位（1位，2位，3位），第一位代表有几个（3个）2D tensor组成，第二位第三位代表每个2Dtensor的形状
print(z.shape)#z是一个由3个3D tensor组成的4D tensor，因此他的shape有四位（1位，2位，3位，4位），第一位代表由3个3Dtensor组成，后三位代表每个3Dtensor的形状

(3, 4)
(3, 3, 4)
(3, 3, 3, 4)


In [33]:
tensor_0_D=np.array(8)
print(tensor_0_D.shape)#0D tensor的shape是（），标量的shape为空
tensor_1_D=np.array([1,2])
print('\n')
print(tensor_1_D.shape)#1D tensor的shape是一个轴（1轴，），一个轴上有两个元素所以是（2，）
tensor_2_D=np.array([[1,2],[1,2]])
print('\n')
print(tensor_2_D.shape)#2D tensor但shape是两个轴（1轴，2轴），轴1是行数：2，轴2是列数：2，因此shape（2，2）
tensor_3_D=np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
print('\n')
print(tensor_3_D.shape)#3Dtensor的形状是3个轴，轴1是由几个2Dtensor组成：2，轴2是2Dtensor的行数：2，轴2是2Dtensor的列数：2，因此（2，2，2）
tensor_3_D_1=np.array([[[2,2,2],[2,2,2]],[[1,1,1],[1,1,1]]]) #(2,2,3)
print('\n')
print(tensor_3_D_1.shape)

()


(2,)


(2, 2)


(2, 2, 2)


(2, 2, 3)


In [35]:
print(tensor_0_D.dtype)
print('\n')
tensor_1_D=np.array([1.,2.])
print(tensor_1_D.dtype)
print('\n')
print(tensor_2_D.dtype)
print('\n')
print(tensor_3_D.dtype)

int64


float64


int64


int64
